
server:
  port: 9002

management:
  port: 9902

spring:
  application:
    name: cloud-turbine
  profiles:
      #   \u9ED8\u8BA4\u7684profile\u4E3Adev\uFF0C\u5176\u4ED6\u73AF\u5883\u901A\u8FC7\u6307\u5B9A\u542F\u52A8\u53C2\u6570\u4F7F\u7528\u4E0D\u540C\u7684profile\uFF0C\u6BD4\u5982\uFF1A
      #   \u6D4B\u8BD5\u73AF\u5883\uFF1Ajava -jar eureka-server.jar --spring.profiles.active=test
      #   \u751F\u4EA7\u73AF\u5883\uFF1Ajava -jar eureka-server.jar --spring.profiles.active=prod
    active: dev

---

spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true
      # \u5FC3\u8DF3\u68C0\u6D4B\u68C0\u6D4B\u4E0E\u7EED\u7EA6\u65F6\u95F4   \u6D4B\u8BD5\u65F6\u5C06\u503C\u8BBE\u7F6E\u8BBE\u7F6E\u5C0F\u4E9B\uFF0C\u4FDD\u8BC1\u670D\u52A1\u5173\u95ED\u540E\u6CE8\u518C\u4E2D\u5FC3\u80FD\u53CA\u65F6\u8E22\u51FA\u670D\u52A1
#      lease-renewal-interval-in-seconds: 1 # \u6BCF\u95F4\u96941s\uFF0C\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3\uFF0C\u8BC1\u660E\u81EA\u5DF1\u4F9D\u7136\u201D\u5B58\u6D3B\u201C.\u5FC3\u8DF3\u65F6\u95F4\uFF0C\u5373\u670D\u52A1\u7EED\u7EA6\u95F4\u9694\u65F6\u95F4\uFF08\u7F3A\u7701\u4E3A30s\uFF09
#      lease-expiration-duration-in-seconds: 2 #  \u544A\u8BC9\u670D\u52A1\u7AEF\uFF0C\u5982\u679C\u62112s\u4E4B\u5185\u6CA1\u6709\u7ED9\u4F60\u53D1\u5FC3\u8DF3\uFF0C\u5C31\u4EE3\u8868\u6211\u201C\u6B7B\u201D\u4E86\uFF0C\u5C06\u6211\u8E22\u51FA\u6389\u3002\uFF08\u7F3A\u7701\u4E3A90s\uFF09
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health

turbine:
  app-config: user-controller
  cluster-name-expression: new String("default1")
  combine-host-port: true


---
spring:
  profiles: prod

eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.0.101:8761/eureka/
    instance:
      prefer-ip-address: true

turbine:
  app-config: user-controller
  cluster-name-expression: new String("default")
  combine-host-port: true