
server:
  port: 9002


spring:
  application:
    name: cloud-turbine
  profiles:
      #   默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
      #   测试环境：java -jar eureka-server.jar --spring.profiles.active=test
      #   生产环境：java -jar eureka-server.jar --spring.profiles.active=prod
    active: dev
management:
  port: 9902

#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#  +++++++++++++++++++++++++ start  profile.active = dev  +++++++++++++++++++++++
#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
---

spring:
  profiles: dev
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
    #  defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/
#      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true
      # 心跳检测检测与续约时间   测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
#      lease-renewal-interval-in-seconds: 1 # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“.心跳时间，即服务续约间隔时间（缺省为30s）
#      lease-expiration-duration-in-seconds: 2 #  告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。（缺省为90s）
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health

turbine:
  app-config: user-controller
  cluster-name-expression: new String("default1")
  combine-host-port: true

#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#  +++++++++++++++++++++++++ start  profile.active = prod  ++++++++++++++++++++++
#  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
---
spring:
  profiles: prod

eureka:
    client:
        serviceUrl:
          #  defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
            defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/
#            defaultZone: http://192.168.0.101:8761/eureka/

    instance:
      prefer-ip-address: true

turbine:
  app-config: user-controller
  cluster-name-expression: new String("default")
  combine-host-port: true