security:
  oauth2:
    client:
      client-id: resource1
      client-secret: secret
      user-authorization-uri: http://localhost:9005/oauth/authorize
      grant-type: password
      scope: read
      access-token-uri: http://localhost:9005/oauth/token

    resource:
      user-info-uri: http://localhost:9005/user

    authorization:
      check-token-access: http://localhost:9005/oauth/check_token

    basic:
      enabled: false
